// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHNfRRiIJ5_at0lYLaon0OGvAnLE25t54',
    appId: '1:953164292674:web:6b07a048ae5a81227843db',
    messagingSenderId: '953164292674',
    projectId: 'fir-abir-e6326',
    authDomain: 'fir-abir-e6326.firebaseapp.com',
    databaseURL: 'https://fir-abir-e6326-default-rtdb.firebaseio.com',
    storageBucket: 'fir-abir-e6326.firebasestorage.app',
    measurementId: 'G-BN0NCRQPLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdRo3qiFf3wNvF_MBsCK1dKvy1mF3XqW4',
    appId: '1:953164292674:android:28e11c3af0f09ceb7843db',
    messagingSenderId: '953164292674',
    projectId: 'fir-abir-e6326',
    databaseURL: 'https://fir-abir-e6326-default-rtdb.firebaseio.com',
    storageBucket: 'fir-abir-e6326.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhQzCvIgcrTBiqONeQwFxYF4I_UYeymXc',
    appId: '1:953164292674:ios:fcf86823cc76da9e7843db',
    messagingSenderId: '953164292674',
    projectId: 'fir-abir-e6326',
    databaseURL: 'https://fir-abir-e6326-default-rtdb.firebaseio.com',
    storageBucket: 'fir-abir-e6326.firebasestorage.app',
    iosBundleId: 'com.abir.notificationFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhQzCvIgcrTBiqONeQwFxYF4I_UYeymXc',
    appId: '1:953164292674:ios:fcf86823cc76da9e7843db',
    messagingSenderId: '953164292674',
    projectId: 'fir-abir-e6326',
    databaseURL: 'https://fir-abir-e6326-default-rtdb.firebaseio.com',
    storageBucket: 'fir-abir-e6326.firebasestorage.app',
    iosBundleId: 'com.abir.notificationFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHNfRRiIJ5_at0lYLaon0OGvAnLE25t54',
    appId: '1:953164292674:web:a6540d65b06d16457843db',
    messagingSenderId: '953164292674',
    projectId: 'fir-abir-e6326',
    authDomain: 'fir-abir-e6326.firebaseapp.com',
    databaseURL: 'https://fir-abir-e6326-default-rtdb.firebaseio.com',
    storageBucket: 'fir-abir-e6326.firebasestorage.app',
    measurementId: 'G-0J4W2FXHQR',
  );
}
